export const metadata = {
    title: 'About Page',
    description: 'Generated by create next app',
}

export default function About() {
    return (
        <div className="">About Page</div>
    )
}